version: "2"
run:
  concurrency: 8
  modules-download-mode: readonly
  tests: true
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - gocyclo
    - govet
    - maintidx
    - misspell
    - unparam
    - unused
  settings:
    funlen:
      lines: 100
      statements: 80
    gocritic:
      disabled-checks:
        - exitAfterDefer
    gocyclo:
      min-complexity: 30
    gosec:
      severity: medium
      config:
        G301: "0755"
        G302: "0644"
        G306: "0644"
    maintidx:
      under: 25
    misspell:
      locale: US
    nestif:
      min-complexity: 4
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
severity:
  default: warning
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
