name: run-goreleaser

on:
  push:
    # run only against tags
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  artifact-build:
    runs-on: ubuntu-latest
    env:
      GO_VERSION: "~1.23"
      GO111MODULE: "on"
      GORELEASER_DISTRIBUTION: "goreleaser"

    strategy:
      fail-fast: false

    steps:

      - name: Install Task
        uses: arduino/setup-task@v2

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      # validate the configuration file
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: ${{ env.GORELEASER_DISTRIBUTION }}
          version: latest
          args: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}

      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: ${{ env.GORELEASER_DISTRIBUTION }}
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
